/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vargas_tamayo_advjava_proj2;



/*
Class name: CarGUI

Class Author: Luis E. Vargas Tamayo

Purpose of the class: The interactive I/O that creates the virtual vehicle for the user

Date:  9/15/2017

List of changes with dates: none

Special Notes: none
*/ 

public class DriveCarGUI extends javax.swing.JFrame 
{

    private Car newCar;

    /*
    Method Name: DriveCarGUI()
    Purpose: This is the COntructor that creates the GUI
    Parameter: Car newCar
    Method Input: initComponents()
    Return Value: none
    Date: 9/15/2017
    */ 
    public DriveCarGUI(Car newCar)
    {
        initComponents();
        this.newCar = newCar;
        txtTypeCar.setText(newCar.getAttritube());// the title will display the selected attributes from the user on the screen
        DriveCarPanel.setBackground(newCar.getColor()); // the selected color will be the background
    }
    
    /*
    Method Name: DriveCarGUI()
    Purpose: This is an exception // it was generated automatically because my GUI has a parameter
    Parameter: none
    Method Input: none
    Return Value: none
    Date: 9/15/2017
    */ 
    private DriveCarGUI() 
    {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    

    
    
    
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DriveCarPanel = new javax.swing.JPanel();
        btnBrake = new javax.swing.JButton();
        btnAccelerate = new javax.swing.JButton();
        txtSpeedDisplay = new javax.swing.JTextField();
        btnNewCar = new javax.swing.JButton();
        txtTypeCar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1250, 1000));
        setMinimumSize(new java.awt.Dimension(1250, 1000));
        setResizable(false);

        DriveCarPanel.setBackground(new java.awt.Color(204, 204, 255));
        DriveCarPanel.setMaximumSize(new java.awt.Dimension(1250, 1000));
        DriveCarPanel.setMinimumSize(new java.awt.Dimension(1250, 1000));

        btnBrake.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnBrake.setText("Brake");
        btnBrake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrakeActionPerformed(evt);
            }
        });

        btnAccelerate.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnAccelerate.setText("Accelerate");
        btnAccelerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAccelerateActionPerformed(evt);
            }
        });

        txtSpeedDisplay.setEditable(false);
        txtSpeedDisplay.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        txtSpeedDisplay.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSpeedDisplay.setText("0");

        btnNewCar.setFont(new java.awt.Font("Tahoma", 0, 25)); // NOI18N
        btnNewCar.setText("Drive A New Car");
        btnNewCar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCarActionPerformed(evt);
            }
        });

        txtTypeCar.setEditable(false);
        txtTypeCar.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        txtTypeCar.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 35)); // NOI18N
        jLabel1.setText("MPH");

        javax.swing.GroupLayout DriveCarPanelLayout = new javax.swing.GroupLayout(DriveCarPanel);
        DriveCarPanel.setLayout(DriveCarPanelLayout);
        DriveCarPanelLayout.setHorizontalGroup(
            DriveCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriveCarPanelLayout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(DriveCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTypeCar)
                    .addGroup(DriveCarPanelLayout.createSequentialGroup()
                        .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(btnAccelerate, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(144, 144, 144))
            .addGroup(DriveCarPanelLayout.createSequentialGroup()
                .addGroup(DriveCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DriveCarPanelLayout.createSequentialGroup()
                        .addGap(460, 460, 460)
                        .addComponent(btnNewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(DriveCarPanelLayout.createSequentialGroup()
                        .addGap(374, 374, 374)
                        .addComponent(txtSpeedDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DriveCarPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(425, 425, 425))
        );
        DriveCarPanelLayout.setVerticalGroup(
            DriveCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DriveCarPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTypeCar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtSpeedDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addGroup(DriveCarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAccelerate, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrake, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addComponent(btnNewCar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DriveCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DriveCarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  
    /*
    Method Name: btnBrakeActionPerformed()
    Purpose: decreased the speed
    Parameter: none
    Method Input: none
    Return Value: none
    Date: 9/15/2017
    */ 
    private void btnBrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrakeActionPerformed
  
        newCar.brake();// slows down speed
        txtSpeedDisplay.setText(String.valueOf(newCar.getSpeed())); //prints new speed
        
    }//GEN-LAST:event_btnBrakeActionPerformed
   
    /*
    Method Name: btnAccelerateActionPerformed()
    Purpose: increased the speed
    Parameter: none
    Method Input: none
    Return Value: none
    Date: 9/15/2017
    */ 
    private void btnAccelerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAccelerateActionPerformed
        
        newCar.acceleration();//increased speed
        txtSpeedDisplay.setText(String.valueOf(newCar.getSpeed())); //prints new speed
        
    }//GEN-LAST:event_btnAccelerateActionPerformed
   
    /*
    Method Name: btnNewCarActionPerformed()
    Purpose:  closes GUI
    Parameter: none
    Method Input: none
    Return Value: none
    Date: 9/15/2017
    */ 
    private void btnNewCarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCarActionPerformed
     
        this.dispose(); // closes this GUI
        
    }//GEN-LAST:event_btnNewCarActionPerformed

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DriveCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DriveCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DriveCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DriveCarGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DriveCarGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DriveCarPanel;
    private javax.swing.JButton btnAccelerate;
    private javax.swing.JButton btnBrake;
    private javax.swing.JButton btnNewCar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtSpeedDisplay;
    private javax.swing.JTextField txtTypeCar;
    // End of variables declaration//GEN-END:variables
}
